biru/urls.py
from django.urls import path
from biru.views import *

app_name = 'biru'

urlpatterns = [
    path('api/beli-voucher', beli_voucher, name='beli_voucher')
]

merah/urls.py
from django.urls import path
from merah.views import *

app_name = 'merah'

urlpatterns = [
    path('transaksi/', view_transaction_form, name="show_transaction_form"),
    path('transfer/', transfer, name="transfer"),
    path('payment/', payment, name="payment"),
    path('topup/', topup, name="topup"),
    path('withdraw/', withdraw, name="withdraw"),
    path('api/get-order', get_order, name="get_order"),
    path('', view_mypay, name='show_mypay')
]

sijarta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('subkategori/', include('hijau.urls', namespace='subkategori')),
    path('mypay/', include('merah.urls', namespace='mypay')),
    path('biru/', include('biru.urls',  namespace='biru'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>
    {% block meta %} {% endblock meta %}
  </head>

  <body>
    {% include 'navbar.html'%}
    {% block content %}  {% endblock content %}
  </body>
</html>

templates/navbar.html
<nav class="bg-white shadow-xl">
    <div class="flex justify-between px-6">
        <div class="flex space-x-7">
            <a href="{% url 'home' %}" class="flex items-center py-2">
                <!-- SIJARTA dengan gaya gradasi yang sama seperti homepage -->
                <span class="font-extrabold text-2xl text-transparent bg-clip-text bg-gradient-to-r from-[#3163ea] to-blue-600">
                    Sijarta
                </span>
            </a>
        </div>

        <div class="hidden md:flex items-center py-3 ml-24 space-x-4">
            {% if logged_in %}
                <a href="{% url 'home' %}" class="px-8 py-3 border-2 border-[#3163ea] text-[#3163ea] rounded-full hover:bg-[#3163ea] hover:text-white transition-colors duration-300" onclick="setActiveButton(this)">
                    Home
                </a>
                <a href="{% url 'mypay:show_mypay' %}" class="px-8 py-3 border-2 border-[#3163ea] text-[#3163ea] rounded-full hover:bg-[#3163ea] hover:text-white transition-colors duration-300" onclick="setActiveButton(this)">
                    MyPay
                </a>

                {% if is_pelanggan %}
                    <a href="{% url 'kelola_status_pesanan' user.0 %}" class="px-8 py-3 border-2 border-[#3163ea] text-[#3163ea] rounded-full hover:bg-[#3163ea] hover:text-white transition-colors duration-300" onclick="setActiveButton(this)">
                        Kelola Pesanan Saya
                    </a>
                    <a href="{% url 'diskon' %}" class="px-8 py-3 border-2 border-[#3163ea] text-[#3163ea] rounded-full hover:bg-[#3163ea] hover:text-white transition-colors duration-300" onclick="setActiveButton(this)">
                        Diskon
                    </a>
                {% else %}
                    <a href="{% url 'pekerjaan_jasa' %}" class="px-8 py-3 border-2 border-[#3163ea] text-[#3163ea] rounded-full hover:bg-[#3163ea] hover:text-white transition-colors duration-300" onclick="setActiveButton(this)">
                        Kelola Pekerjaan Saya
                    </a>
                    <a href="{% url 'status_pekerjaan_jasa' %}" class="px-8 py-3 border-2 border-[#3163ea] text-[#3163ea] rounded-full hover:bg-[#3163ea] hover:text-white transition-colors duration-300" onclick="setActiveButton(this)">
                        Kelola Status Pekerjaan
                    </a>
                {% endif %}
                <a href="{% url 'profile' user.0 %}" class="px-8 py-3 border-2 border-[#3163ea] text-[#3163ea] rounded-full hover:bg-[#3163ea] hover:text-white transition-colors duration-300" onclick="setActiveButton(this)">
                    Profil
                </a>
            {% else %}
                <div class="flex items-center space-x-3">
                    <a href="{% url 'login' %}" class="px-8 py-3 border-2 border-[#3163ea] text-[#3163ea] rounded-full hover:bg-[#3163ea] hover:text-white transition-colors duration-300">
                        Login
                    </a>
                    <a href="{% url 'register' %}" class="px-8 py-3 border-2 border-[#3163ea] text-[#3163ea] rounded-full hover:bg-[#3163ea] hover:text-white transition-colors duration-300">
                        Register
                    </a>
                </div>
            {% endif %}
        </div>

        {% if logged_in %}
        <div class="md:flex hidden items-center space-x-2">
            <p class="py-2 px-4 font-medium text-xl text-gray-700 rounded transition duration-300">
                {{ user.1 }}
                {% if is_pelanggan or user_who_access_is_pelanggan %}
                (Pelanggan)
                {% else %}
                (Pekerja)
                {% endif %}
            </p>
            <!-- Tombol Logout di sini -->
            <a href="{% url 'logout' %}" class="px-8 py-3 border-2 border-red-500 text-red-500 rounded-full hover:bg-red-500 hover:text-white transition-colors duration-300" onclick="setActiveButton(this)">
                Logout
            </a>
        </div>
        {% endif %}

        <div class="md:hidden flex items-center">
            <button class="outline-none mobile-menu-button">
                <svg class="w-6 h-6 text-gray-500 hover:text-gray-900" 
                     x-show="!showMenu"
                     fill="none" 
                     stroke-linecap="round" 
                     stroke-linejoin="round" 
                     stroke-width="2" 
                     viewBox="0 0 24 24" 
                     stroke="currentColor">
                    <path d="M4 6h16M4 12h16M4 18h16"></path>
                </svg>
            </button>
        </div>
    </div>

    <!-- Mobile Menu -->
    <div class="hidden mobile-menu md:hidden">
        <ul class="px-4 pt-2 pb-3 space-y-1 sm:px-3">
            {% if logged_in %}
                <li>
                    <a href="{% url 'home' %}" class="block px-3 py-2 rounded text-gray-500 hover:text-gray-900 hover:bg-gray-100 transition duration-300">Home</a>
                </li>
                <li>
                    <a href="#" class="block px-3 py-2 rounded text-gray-500 hover:text-gray-900 hover:bg-gray-100 transition duration-300">MyPay</a>
                </li>
                
                {% if is_pelanggan %}
                    <li>
                        <a href="#" class="block px-3 py-2 rounded text-gray-500 hover:text-gray-900 hover:bg-gray-100 transition duration-300">Kelola Pesanan Saya</a>
                    </li>
                    <li>
                        <a href="#" class="block px-3 py-2 rounded text-gray-500 hover:text-gray-900 hover:bg-gray-100 transition duration-300">Diskon</a>
                    </li>
                {% else %}
                    <li>
                        <a href="#" class="block px-3 py-2 rounded text-gray-500 hover:text-gray-900 hover:bg-gray-100 transition duration-300">Kelola Pekerjaan Saya</a>
                    </li>
                    <li>
                        <a href="#" class="block px-3 py-2 rounded text-gray-500 hover:text-gray-900 hover:bg-gray-100 transition duration-300">Kelola Status Pekerjaan</a>
                    </li>
                {% endif %}
                
                <li>
                    <a href="{% url 'profile' user.0 %}" class="block px-3 py-2 rounded text-gray-500 hover:text-gray-900 hover:bg-gray-100 transition duration-300">Profil</a>
                </li>
                <li>
                    <a href="{% url 'logout' %}" class="block px-3 py-2 rounded text-white bg-red-500 hover:bg-red-600 transition duration-300">Logout</a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'login' %}" class="block px-3 py-2 hover:text-blue-600 hover:bg-blue-100 transition duration-300">Login</a>
                </li>
                <li>
                    <a href="{% url 'register' %}" class="block px-3 py-2 rounded hover:bg-blue-100 transition duration-300">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<script>
    const btn = document.querySelector("button.mobile-menu-button");
    const menu = document.querySelector(".mobile-menu");

    btn.addEventListener("click", () => {
        menu.classList.toggle("hidden");
    });

    // Function to highlight the last clicked button
    function setActiveButton(button) {
        // Remove active class from all buttons
        const buttons = document.querySelectorAll(".md\\:flex a");
        buttons.forEach(btn => btn.classList.remove("bg-blue-500", "text-white"));

        // Add active class to the clicked button
        button.classList.add("bg-blue-500", "text-white");
    }
</script>